fixtures:
  forge_modules:
    firewall: 
      repo: "puppetlabs/firewall"
      ref:  "1.2.0"
    java: 
      repo: "puppetlabs/java"
      ref:  "1.1.1"
    stdlib: 
      repo: "puppetlabs/stdlib"
      ref:  "4.2.1"
  symlinks:
      mirthconnect: "#{source_dir}"
