fixtures:
  repositories:
    java:
      git://github.com/puppetlabs/puppetlabs-java.git
    firewall:
      git://github.com/puppetlabs/puppetlabs-firewall.git
    stdlib:
      git://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
      mirthconnect: "#{source_dir}"
