fixtures:
  forge_modules:
    archive:
      repo: 'puppet/archive'
    firewall: 
      repo: 'puppetlabs/firewall'
    java: 
      repo: 'puppetlabs/java'
    mysql: 
      repo: 'puppetlabs/mysql'
    stdlib: 
      repo: 'puppetlabs/stdlib'
  symlinks:
      mirthconnect: "#{source_dir}"
