---
language: ruby
bundler_args: --without development
script: 'bundle exec rake' #rspec and lint tests
gemfile: .travis/Gemfile
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.4.0"
    - PUPPET_GEM_VERSION="~> 3.5.0"
    - PUPPET_GEM_VERSION="~> 3.6.0"
    - PUPPET_GEM_VERSION="~> 3.7.0"
matrix:
  email: false
