---
language: ruby
bundler_args: --without development
script: 'bundle exec rake' #rspec and lint tests
gemfile: .travis/Gemfile
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 2.7.0"
    - PUPPET_GEM_VERSION="~> 3.0.0"
    - PUPPET_GEM_VERSION="~> 3.1.0"
    - PUPPET_GEM_VERSION="~> 3.2.0"
    - PUPPET_GEM_VERSION="~> 3.3.0"
    - PUPPET_GEM_VERSION="~> 3.4.0"
matrix:
  exclude:
     - rvm: 1.9.3
       env: PUPPET_GEM_VERSION="~> 2.7.0"
     - rvm: 1.9.3
       env: PUPPET_GEM_VERSION="~> 3.0.0"
     - rvm: 2.0.0
       env: PUPPET_GEM_VERSION="~> 3.1.0"
     - rvm: 2.0.0
       env: PUPPET_GEM_VERSION="~> 3.0.0"
     - rvm: 2.0.0
       env: PUPPET_GEM_VERSION="~> 2.7.0"
     - rvm: 2.1.1
       env: PUPPET_GEM_VERSION="~> 2.7.0"          
     - rvm: 2.1.1
       env: PUPPET_GEM_VERSION="~> 3.0.0"
     - rvm: 2.1.1
       env: PUPPET_GEM_VERSION="~> 3.1.0"
     - rvm: 2.1.1
       env: PUPPET_GEM_VERSION="~> 3.2.0"
     - rvm: 2.1.1
       env: PUPPET_GEM_VERSION="~> 3.3.0"
  email: false
