name         'myoung34-mirthconnect'
version      '0.0.4'
source       'http://github.com/myoung34/puppet-mirthconnect'
author       'Marcus Young'
license      'GPLv3+'
summary      'Puppet MirthConnect management module'
description  'This module can be used for basic MirthConnect installation'
project_page 'http://github.com/myoung34/puppet-mirthconnect'

dependency 'puppetlabs/stdlib',   '>= 4.2.1'
dependency 'puppetlabs/firewall', '>= 1.1.0'
dependency 'puppetlabs/java',     '>= 1.1.1'
