source 'http://rubygems.org'

group :development do
  gem 'rake',                    '>=0.9.2.2'
end

group :rake do
  gem 'beaker-rspec'
  gem 'coveralls', require: false
  gem 'puppet-blacksmith'
  gem 'puppet-lint',             '>=0.1.12'
  gem 'puppetlabs_spec_helper'
  gem 'rspec-puppet',            '>=0.1.3'
end

if puppetversion = ENV['PUPPET_GEM_VERSION']
  gem 'puppet', puppetversion, :require => false
else
  gem 'puppet', :require => false
end 
