---
HOSTS:
  centos-65-x64:
    roles:
      - master
    platform: centos-65-x64-virtualbox-puppet
    box: centos-65-x64-virtualbox-puppet
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box
    hypervisor: vagrant
    distmoduledir: /etc/puppet/modules
